# Generated by Django 2.0.3 on 2018-03-24 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('doc_number', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('created_on', models.DateTimeField(verbose_name='created on')),
                ('doc_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentlist.DocType')),
            ],
        ),
    ]
