# Generated by Django 2.0.3 on 2018-04-03 01:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentlist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='updated_on',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='updated on'),
        ),
        migrations.AlterField(
            model_name='student',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created on'),
        ),
    ]
