# Generated by Django 2.0.5 on 2018-05-16 13:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('studentlist', '0002_auto_20180403_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='updated_on',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='updated on'),
        ),
    ]
